[tool.poetry]
name = "tjl"
version = "0.1.0"
description = ""
authors = ["TJ Bai <tbai4@jh.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.scripts]
tjl = "tjl.tjl:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
